insert into books (id, name, description, price, author, genre, publisher, pageCount, imageUrl) values (1000, 'The Lincoln Conspiracy: The Secret Plot to Kill America''s 16th President-and Why It Failed', 'Everyone knows the story of Abraham Lincoln''s assassination in 1865, but few are aware of the original conspiracy to kill him four years earlier in 1861, literally on his way to Washington, D.C., for his first inauguration. The conspirators were part of a pro-Southern secret society that didn’t want an antislavery President in the White House. They planned an elaborate scheme to assassinate the brand new President in Baltimore as Lincoln''s inauguration train passed through en route to the Capitol. The plot was investigated by famed detective Allan Pinkerton, who infiltrated the group with undercover agents, including one of the first female private detectives in America. Had the assassination succeeded, there would have been no Lincoln Presidency, and the course of the Civil War and American history would have forever been altered.', 17.99, 'Brad Meltzer', 'History', 'Flatiron Books', 448, 'https://m.media-amazon.com/images/I/51i88SW9+VL.jpg');

insert into books (id, name, description, price, author, genre, publisher, pageCount, imageUrl) values (1001, 'Homebody: A Guide to Creating Spaces You Never Want to Leave', 'In Homebody: A Guide to Creating Spaces You Never Want to Leave, Joanna Gaines walks you through how to create a home that reflects the personalities and stories of the people who live there. Using examples from her own farmhouse as well as a range of other homes, this comprehensive guide will help you assess your priorities and instincts, as well as your likes and dislikes, with practical steps for navigating and embracing your authentic design style. Room by room, Homebody gives you an in-depth look at how these styles are implemented as well as how to blend the looks you''re drawn to in order to create spaces that feel distinctly yours. A removable design template at the back of the book offers a step-by-step guide to planning and sketching out your own design plans. The insight shared in Homebody will instill in you the confidence to thoughtfully create spaces you never want to leave.', 23.95, 'Joanna Gaines', 'Architecture', 'Harper Design', 352, 'https://images-na.ssl-images-amazon.com/images/I/51PfPNbYWLL._SX391_BO1,204,203,200_.jpg');

insert into books (id, name, description, price, author, genre, publisher, pageCount, imageUrl) values (1002, 'My First Learn to Write Workbook: Practice for Kids with Pen Control, Line Tracing, Letters, and More! (Kids coloring activity books)', 'Set kids up to succeed in school with a learn to write for kids guide that teaches them letters, shapes, and numbers―and makes it fun. My First Learn-to-Write Workbook introduces your early writer to proper pen control, steady line tracing, new words, and more with dozens of exercises that will engage their minds and boost their reading and writing comprehension skills.', 5.39, 'Crystal Radke', 'Education & Teaching', 'Rockridge Press', 84, 'https://images-na.ssl-images-amazon.com/images/I/51joYbBW7DL._SX384_BO1,204,203,200_.jpg');

insert into books (id, name, description, price, author, genre, publisher, pageCount, imageUrl) values (1003, 'Start with Why: How Great Leaders Inspire Everyone to Take Action', 'In 2009 Simon Sinek started a movement to help people become more inspired at work and, in turn, inspire their colleagues and customers. Since then, millions have been touched by the power of his ideas, including more than 28 million who''ve watched his TED Talk based on Start with Why - the third most popular TED video of all time. Sinek starts with a fundamental question: Why are some people and organizations more innovative, more influential, and more profitable than others? Why do some command greater loyalty from customers and employees alike? Even among the successful, why are so few able to repeat their success over and over? People like Martin Luther King Jr., Steve Jobs, and the Wright Brothers had little in common, but they all started with why. They realized that people won''t truly buy into a product, service, movement, or idea until they understand the why behind it. Start with Why shows that the leaders who''ve had the greatest influence in the world all think, act, and communicate the same way - and it''s the opposite of what everyone else does. Sinek calls this powerful idea The Golden Circle, and it provides a framework upon which organizations can be built, movements can be led, and people can be inspired. And it all starts with why.', 12.99, 'Simon Sinek', 'Computer & Technology', 'Penguin Audio', 690, 'https://m.media-amazon.com/images/I/51Zuy0g7l+L.jpg');

insert into books (id, name, description, price, author, genre, publisher, pageCount, imageUrl) values (1004, 'Adobe Photoshop Classroom in a Book (2020 release)', 'Creative professionals seeking the fastest, easiest, most comprehensive way to learn Adobe Photoshop choose Adobe Photoshop Classroom in a Book (2020 release) from Adobe Press. The 15 project-based lessons show key step-by-step techniques for working in Photoshop, including how to correct, enhance, and distort digital images, create image composites, and prepare images for print and the web. In addition to learning the essential elements of the Photoshop interface, this revised edition for the 2020 release covers features like the new Object Selection tool, saving Cloud Documents for easy access from Photoshop on other devices such as the Apple iPad, removing objects with upgraded Content-Aware Fill, applying styles and objects such as gradients and shapes, instantly using redesigned Presets panels, and much more! The online companion files include all the necessary assets for readers to complete the projects featured in each chapter. All buyers of the book get full access to the Web Edition: A Web-based version of the complete ebook enhanced with video and multiple-choice quizzes', 56.99, 'Andrew Faulkner', 'Computer Graphics & Design', 'Adobe Press', 416, 'https://images-na.ssl-images-amazon.com/images/I/51bXhRDC6sL._SX402_BO1,204,203,200_.jpg');

insert into books (id, name, description, price, author, genre, publisher, pageCount, imageUrl) values (1005, 'Eleanor Oliphant Is Completely Fine: A Novel', 'Meet Eleanor Oliphant: She struggles with appropriate social skills and tends to say exactly what she’s thinking. Nothing is missing in her carefully timetabled life of avoiding social interactions, where weekends are punctuated by frozen pizza, vodka, and phone chats with Mummy.  But everything changes when Eleanor meets Raymond, the bumbling and deeply unhygienic IT guy from her office. When she and Raymond together save Sammy, an elderly gentleman who has fallen on the sidewalk, the three become the kinds of friends who rescue one another from the lives of isolation they have each been living. And it is Raymond’s big heart that will ultimately help Eleanor find the way to repair her own profoundly damaged one. Soon to be a major motion picture produced by Reese Witherspoon, Eleanor Oliphant Is Completely Fine is the smart, warm, and uplifting story of an out-of-the-ordinary heroine whose deadpan weirdness and unconscious wit make for an irresistible journey as she realizes. . .', 9.69, 'Gail Honeyman', 'Romantic Comedy', 'Penguin Books', 352, 'https://images-na.ssl-images-amazon.com/images/I/51meTQ+nUJL._SX330_BO1,204,203,200_.jpg');

insert into books (id, name, description, price, author, genre, publisher, pageCount, imageUrl) values (1006, 'Pride and Prejudice', 'Few have failed to be charmed by the witty and independent spirit of Elizabeth Bennet in Austen’s beloved classic Pride and Prejudice. When Elizabeth Bennet first meets eligible bachelor Fitzwilliam Darcy, she thinks him arrogant and conceited; he is indifferent to her good looks and lively mind. When she later discovers that Darcy has involved himself in the troubled relationship between his friend Bingley and her beloved sister Jane, she is determined to dislike him more than ever. In the sparkling comedy of manners that follows, Jane Austen shows us the folly of judging by first impressions and superbly evokes the friendships, gossip and snobberies of provincial middle-class life. This Penguin Classics edition, based on Austen''s first edition, contains the original Penguin Classics introduction by Tony Tanner and an updated introduction and notes by Viven Jones. For more than seventy years, Penguin has been the leading publisher of classic literature in the English-speaking world. With more than 1,700 titles, Penguin Classics represents a global bookshelf of the best works throughout history and across genres and disciplines. Readers trust the series to provide authoritative texts enhanced by introductions and notes by distinguished scholars and contemporary authors, as well as up-to-date translations by award-winning translators.', 10.64, 'Jane Austen', 'Regency Romances', 'Penguin Books', 480, 'https://images-na.ssl-images-amazon.com/images/I/41LHdGM1FCL._SX326_BO1,204,203,200_.jpg');

insert into books (id, name, description, price, author, genre, publisher, pageCount, imageUrl) values (1007, 'Netter''s Anatomy Coloring Book Updated Edition (Netter Basic Science)', 'Learn and master anatomy with ease, while having fun, through the unique approach of Netter''s Anatomy Coloring Book, 2nd Edition. You can trace arteries, veins, and nerves through their courses and bifurcations...reinforce your understanding of muscle origins and insertions from multiple views and dissection layers...and develop a better understanding of the integration of individual organs in the workings of each body system throughout the human form. Whether you are taking an anatomy course or just curious about how the body works, let the art of Netter guide you!', 17.99, 'John T. Hansen PhD', 'Medical Reference', 'Elsevier', 392, 'https://images-na.ssl-images-amazon.com/images/I/51RzV6DbSlL._SX389_BO1,204,203,200_.jpg');

insert into books (id, name, description, price, author, genre, publisher, pageCount, imageUrl) values (1008, 'Thinking, Fast and Slow', 'In the international bestseller, Thinking, Fast and Slow, Daniel Kahneman, the renowned psychologist and winner of the Nobel Prize in Economics, takes us on a groundbreaking tour of the mind and explains the two systems that drive the way we think. System 1 is fast, intuitive, and emotional; System 2 is slower, more deliberative, and more logical. The impact of overconfidence on corporate strategies, the difficulties of predicting what will make us happy in the future, the profound effect of cognitive biases on everything from playing the stock market to planning our next vacation―each of these can be understood only by knowing how the two systems shape our judgments and decisions. Engaging the reader in a lively conversation about how we think, Kahneman reveals where we can and cannot trust our intuitions and how we can tap into the benefits of slow thinking. He offers practical and enlightening insights into how choices are made in both our business and our personal lives―and how we can use different techniques to guard against the mental glitches that often get us into trouble. Winner of the National Academy of Sciences Best Book Award and the Los Angeles Times Book Prize and selected by The New York Times Book Review as one of the ten best books of 2011, Thinking, Fast and Slow is destined to be a classic.', 8.99, 'Kahneman', 'Medical Psychology', 'FSG Adult', 499, 'https://images-na.ssl-images-amazon.com/images/I/41xp0Xzej8L._SX326_BO1,204,203,200_.jpg');

insert into books (id, name, description, price, author, genre, publisher, pageCount, imageUrl) values (1009, 'Relationship Goals: How to Win at Dating, Marriage, and Sex', 'Realer than the most real conversation you’ve ever heard on the topic, Michael Todd’s honest, heartfelt, and powerful teaching on relationships has already impacted millions of people in all seasons of life around the world. Now, in Relationship Goals, Michael tells his own story of heartache and healing, unpacks explosive truths from God’s Word, and tells it to you straight to help you win at relationships in every part of your life. Where did the idea for relationships come from in the first place? Does God really care who I hang out with? Is it even possible to avoid relational train wrecks? From his plan for intentional dating to handling break-ups well to doing family instead of just being in a family, Michael tackles the questions we all have about relational success. As he candidly examines our most common pitfalls in relationships and the start-today ways to get past them, Michael helps you align your longings with God’s awesome desires for your life. Now, that’s a good relationship goal.', 24.96, 'Michael Todd', 'Christian Books & Bibles', 'WaterBrook', 208, 'https://images-na.ssl-images-amazon.com/images/I/41GMfml84gL._SX331_BO1,204,203,200_.jpg');

insert into books (id, name, description, price, author, genre, publisher, pageCount, imageUrl) values (1010, 'The Lost Art of Reading Nature''s Signs: Use Outdoor Clues to Find Your Way, Predict the Weather, Locate Water, Track Animals―and Other Forgotten Skills (Natural Navigation)', 'When writer and navigator Tristan Gooley journeys outside, he sees a natural world filled with clues. The roots of a tree indicate the sun’s direction; the Big Dipper tells the time; a passing butterfly hints at the weather; a sand dune reveals prevailing wind; the scent of cinnamon suggests altitude; a budding flower points south. To help you understand nature as he does, Gooley shares more than 850 tips for forecasting, tracking, and more, gathered from decades spent walking the landscape around his home and around the world. Whether you’re walking in the country or city, along a coastline, or by night, this is the ultimate resource on what the land, sun, moon, stars, plants, animals, and clouds can reveal—if you only know how to look!', 9.97, 'Tristan Gooley', 'Travelogues & Travel Essays', 'The Experiment', 416, 'https://images-na.ssl-images-amazon.com/images/I/51orF2IJn8L._SX331_BO1,204,203,200_.jpg');

insert into books (id, name, description, price, author, genre, publisher, pageCount, imageUrl) values (1011, '50 States, 5,000 Ideas: Where to Go, When to Go, What to See, What to Do', 'This richly illustrated book from the travel experts at National Geographic showcases the best travel experiences in every state, from the obvious to the unexpected. Sites include national parks, beaches, hotels, Civil War battlefields, dude ranches, out-of-the-way museums, and more. You''ll discover the world''s longest yard sale in Tennessee, swamp tours in Louisiana, dinosaur trails in Colorado, America''s oldest street in NYC, and the best spot to watch for sea otters on the central California coast. Each entry provides detailed travel information as well as fascinating facts about each state that will help fuel your wanderlust and ensure the best vacation possible. In addition to 50 states in the U.S., the book includes a section on the Canadian provinces and territories.', 16.62, 'Joe Yogerst', 'Travel Reference & Tips', 'National Geographic', 288, 'https://images-na.ssl-images-amazon.com/images/I/51b2B4IHwBL._SX389_BO1,204,203,200_.jpg');

insert into books (id, name, description, price, author, genre, publisher, pageCount, imageUrl) values (1012, 'Demon Slayer: Kimetsu no Yaiba, Vol. 2', 'Tanjiro sets out on the path of the Demon Slayer to save his sister and avenge his family! In Taisho-era Japan, Tanjiro Kamado is a kindhearted boy who makes a living selling charcoal. But his peaceful life is shattered when a demon slaughters his entire family. His little sister Nezuko is the only survivor, but she has been transformed into a demon herself! Tanjiro sets out on a dangerous journey to find a way to return his sister to normal and destroy the demon who ruined his life. During final selection for the Demon Slayer Corps, Tanjiro faces a disfigured demon and uses the techniques taught by his master, Urokodaki! As Tanjiro begins to walk the path of the Demon Slayer, his search for the demon who murdered his family leads him to investigate the disappearances of young girls in a nearby town.', 7.57, 'Koyoharu Gotouge', 'Comics & Graphic Novels', 'VIZ Media LLC', 192, 'https://images-na.ssl-images-amazon.com/images/I/61D+0Qv6afL._SX331_BO1,204,203,200_.jpg');

insert into books (id, name, description, price, author, genre, publisher, pageCount, imageUrl) values (1013, 'Kids Summer Academy by ArgoPrep - Grades 6-7: 12 Weeks of Math, Reading, Science, Logic, Fitness and Yoga | Online Access Included | Prevent Summer Learning Loss', 'Our workbook has been carefully designed and crafted by licensed teachers to give students  an incredible learning experience. Students start off the week with English activities followed by Math practice. Throughout the week, students have several fitness activities to complete. Making sure students stay active is just as important as practicing mathematics. We introduce yoga and other basic fitness activities that any student can complete. Each week includes a science experiment which sparks creativity and allows students to visually understand the concepts. On the last day of each week, students will work on a fun puzzle.', 19.99, 'Argo Brothers', 'Geometry & Topology', 'Argo Brothers', 298, 'https://images-na.ssl-images-amazon.com/images/I/51IRYICnX3L._SX385_BO1,204,203,200_.jpg');

insert into books (id, name, description, price, author, genre, publisher, pageCount, imageUrl) values (1014, 'Calculus: 1,001 Practice Problems For Dummies', '1001 Calculus Practice Problems For Dummies takes you beyond the instruction and guidance offered in Calculus For Dummies, giving you 1001 opportunities to practice solving problems from the major topics in your calculus course. Plus, an online component provides you with a collection of calculus problems presented in multiple-choice format to further help you test your skills as you go.', 19.47, 'Patrick Jones', 'Mathematical Analysis', 'For Dummies', 624, 'https://images-na.ssl-images-amazon.com/images/I/51ib978EDvL._SX398_BO1,204,203,200_.jpg');

insert into books (id, name, description, price, author, genre, publisher, pageCount, imageUrl) values (1015, '1177 B.C.: The Year Civilization Collapsed (Turning Points in Ancient History)', 'In 1177 B.C., marauding groups known only as the "Sea Peoples" invaded Egypt. The pharaoh''s army and navy managed to defeat them, but the victory so weakened Egypt that it soon slid into decline, as did most of the surrounding civilizations. After centuries of brilliance, the civilized world of the Bronze Age came to an abrupt and cataclysmic end. Kingdoms fell like dominoes over the course of just a few decades. No more Minoans or Mycenaeans. No more Trojans, Hittites, or Babylonians. The thriving economy and cultures of the late second millennium B.C., which had stretched from Greece to Egypt and Mesopotamia, suddenly ceased to exist, along with writing systems, technology, and monumental architecture. But the Sea Peoples alone could not have caused such widespread breakdown. How did it happen?', 10.99, 'Eric H. Cline', 'Archaeology', 'Princeton University Press', 264, 'https://images-na.ssl-images-amazon.com/images/I/51yRZ4grMYL._SX325_BO1,204,203,200_.jpg');

insert into books (id, name, description, price, author, genre, publisher, pageCount, imageUrl) values (1016, 'Until the End of Time: Mind, Matter, and Our Search for Meaning in an Evolving Universe', 'Until the End of Time is Brian Greene''s breathtaking new exploration of the cosmos and our quest to find meaning in the face of this vast expanse. Greene takes us on a journey from the big bang to the end of time, exploring how lasting structures formed, how life and mind emerged, and how we grapple with our existence through narrative, myth, religion, creative expression, science, the quest for truth, and a deep longing for the eternal. From particles to planets, consciousness to creativity, matter to meaning—Brian Greene allows us all to grasp and appreciate our fleeting but utterly exquisite moment in the cosmos.', 21.04, 'Brian Greene', 'Physics', 'Knopf', 448, 'https://images-na.ssl-images-amazon.com/images/I/51dcn8xo9IL._SX340_BO1,204,203,200_.jpg');

insert into books (id, name, description, price, author, genre, publisher, pageCount, imageUrl) values (1017, 'Magnolia Table, Volume 2: A Collection of Recipes for Gathering', 'Following the launch of her #1 New York Times bestselling cookbook, Magnolia Table, and seeing her family’s own sacred dishes being served at other families’ tables across the country, Joanna Gaines gained a deeper commitment to the value of food being shared. This insight inspired Joanna to get back in the kitchen and start from scratch, pushing herself beyond her comfort zone to develop new recipes for her family, and yours, to gather around. Magnolia Table, Volume 2 is filled with 145 new recipes from her own home that she shares with husband Chip and their five kids, and from the couple’s restaurant, Magnolia Table; Silos Baking Co; and new coffee shop, Magnolia Press. From breakfast to dinner, plus breads, soups, and sides, Magnolia Table, Volume 2 gives readers abundant reasons to gather together.', 21.00, 'Joanna Gaines', 'Cookbooks, Food & Wine', 'William Morrow Cookbooks', 352, 'https://images-na.ssl-images-amazon.com/images/I/41W+DpFKNbL._SX393_BO1,204,203,200_.jpg');

insert into books (id, name, description, price, author, genre, publisher, pageCount, imageUrl) values (1018, 'Flour Water Salt Yeast: The Fundamentals of Artisan Bread and Pizza', 'There are few things more satisfying than biting into a freshly made, crispy-on-the-outside, soft-and-supple-on-the-inside slice of perfectly baked bread. For Portland-based baker Ken Forkish, well-made bread is more than just a pleasure—it is a passion that has led him to create some of the best and most critically lauded breads and pizzas in the country. In Flour Water Salt Yeast, Forkish translates his obsessively honed craft into scores of recipes for rustic boules and Neapolitan-style pizzas, all suited for the home baker. Forkish developed and tested all of the recipes in his home oven, and his impeccable formulas and clear instructions result in top-quality artisan breads and pizzas that stand up against those sold in the best bakeries anywhere. Whether you’re a total beginner or a serious baker, Flour Water Salt Yeast has a recipe that suits your skill level and time constraints: Start with a straight dough and have fresh bread ready by supper time, or explore pre-ferments with a bread that uses biga or poolish. If you’re ready to take your baking to the next level, follow Forkish’s step-by-step guide to making a levain starter with only flour and water, and be amazed by the delicious complexity of your naturally leavened bread. Pizza lovers can experiment with a variety of doughs and sauces to create the perfect pie using either a pizza stone or a cast-iron skillet. Flour Water Salt Yeast is more than just a collection of recipes for amazing bread and pizza—it offers a complete baking education, with a thorough yet accessible explanation of the tools and techniques that set artisan bread apart. Featuring a tutorial on baker’s percentages, advice for manipulating ingredients ratios to create custom doughs, tips for adapting bread baking schedules to fit your day-to-day life, and an entire chapter that demystifies the levain-making process, Flour Water Salt Yeast is an indispensable resource for bakers who want to make their daily bread exceptional bread.', 18.39, 'Ken Forkish', 'Baking', 'Ten Speed Press', 272, 'https://images-na.ssl-images-amazon.com/images/I/51mgUbcbXIL._SX400_BO1,204,203,200_.jpg');

insert into books (id, name, description, price, author, genre, publisher, pageCount, imageUrl) values (1019, 'The Ride of a Lifetime: Lessons Learned from 15 Years as CEO of the Walt Disney Company', 'This book is about the relentless curiosity that has driven Iger for forty-five years, since the day he started as the lowliest studio grunt at ABC. It’s also about thoughtfulness and respect, and a decency-over-dollars approach that has become the bedrock of every project and partnership Iger pursues, from a deep friendship with Steve Jobs in his final years to an abiding love of the Star Wars mythology. “The ideas in this book strike me as universal” Iger writes. “Not just to the aspiring CEOs of the world, but to anyone wanting to feel less fearful, more confidently themselves, as they navigate their professional and even personal lives.”', 16.89, 'Robert Iger', 'Business & Money', 'Random House', 272, 'https://images-na.ssl-images-amazon.com/images/I/41gr0fllE9L._SX327_BO1,204,203,200_.jpg');

insert into books (id, name, description, price, author, genre, publisher, pageCount, imageUrl) values (1020, 'The One Year Uncommon Life Daily Challenge', 'Strengthen the core of your life and faith on a year-long journey with beloved Super Bowl–winning former head coach Tony Dungy! The One Year Uncommon Life Daily Challenge contains 365 reflections from the #1 New York Times bestselling author on living an “uncommon life” of integrity, honoring your family and friends, creating a life of real significance and impact, and walking with the Lord. This year, step up to the challenge―and dare to be uncommon every day.', 11.69, 'Tony Dungy', 'Football', 'Tyndale Momentum', 384, 'https://images-na.ssl-images-amazon.com/images/I/41G0NK1ExCL._SX331_BO1,204,203,200_.jpg');

insert into books (id, name, description, price, author, genre, publisher, pageCount, imageUrl) values (1021, 'Boundaries Updated and Expanded Edition: When to Say Yes, How to Say No To Take Control of Your Life', 'Does your life feel like it''s out of control? Perhaps you feel like you have to say yes to everyone''s requests. Maybe you find yourself readily taking responsibility for others'' feelings and problems. Or perhaps you focus so much on being loving and unselfish that you''ve forgotten your own limits and limitations. Or maybe it''s all of the above. In the New York Times bestseller, Boundaries, Drs. Henry Cloud and John Townsend help you learn when to say yes and know how to say no in order to take control of your life and set healthy, biblical boundaries with your spouse, children, friends, parents, co-workers, and even yourself.', 11.49, 'Henry Cloud', 'Communication & Social Skills', 'Zondervan', 352, 'https://images-na.ssl-images-amazon.com/images/I/41EV8FWvUSL._SX321_BO1,204,203,200_.jpg');

insert into books (id, name, description, price, author, genre, publisher, pageCount, imageUrl) values (1022, 'If Animals Kissed Good Night', 'What if animals did what YOU do? This bestselling story imagines how animals would kiss their loved ones good night! If animals kissed good night like we do...how would they do it? Giraffe and his calf would stretch their necks high, Wolf and his pup would kiss and then HOWL, and Sloth and her baby would move sooooo sloooowwwww. And across the animal kingdom, every creature would share love in a unique way.', 4.79, 'Ann Whitford Paul', 'Children''s Literature', 'Farrar, Straus and Giroux (BYR)', 34, 'https://images-na.ssl-images-amazon.com/images/I/51iHM-M+ADL._SY498_BO1,204,203,200_.jpg');

insert into books (id, name, description, price, author, genre, publisher, pageCount, imageUrl) values (1023, 'Paint by Sticker Kids: Unicorns & Magic: Create 10 Pictures One Sticker at a Time! Includes Glitter Stickers', 'Paint by Sticker Kids: Unicorns & Magic includes everything kids need to create ten vibrant images, including unicorns, a dragon, a princess, and more.', 6.41, 'Workman Publishing', 'Children''s Arts, Music & Photography Books', 'Workman Publishing Company', 34, 'https://images-na.ssl-images-amazon.com/images/I/51iU+NgrzvL._SX491_BO1,204,203,200_.jpg');

insert into books (id, name, description, price, author, genre, publisher, pageCount, imageUrl) values (1024, 'Elon Musk: Tesla, SpaceX, and the Quest for a Fantastic Future', 'In the spirit of Steve Jobs and Moneyball, Elon Musk is both an illuminating and authorized look at the extraordinary life of one of Silicon Valley''s most exciting, unpredictable, and ambitious entrepreneurs--a real-life Tony Stark--and a fascinating exploration of the renewal of American invention and its new "makers." Elon Musk spotlights the technology and vision of Elon Musk, the renowned entrepreneur and innovator behind SpaceX, Tesla, and SolarCity, who sold one of his Internet companies, PayPal, for $1.5 billion. Ashlee Vance captures the full spectacle and arc of the genius''s life and work, from his tumultuous upbringing in South Africa and flight to the United States to his dramatic technical innovations and entrepreneurial pursuits. Vance uses Musk''s story to explore one of the pressing questions of our age: can the nation of inventors and creators who led the modern world for a century still compete in an age of fierce global competition? He argues that Musk--one of the most unusual and striking figures in American business history--is a contemporary, visionary amalgam of legendary inventors and industrialists including Thomas Edison, Henry Ford, Howard Hughes, and Steve Jobs. More than any other entrepreneur today, Musk has dedicated his energies and his own vast fortune to inventing a future that is as rich and far-reaching as the visionaries of the golden age of science-fiction fantasy. Thorough and insightful, Elon Musk brings to life a technology industry that is rapidly and dramatically changing by examining the life of one of its most powerful and influential titans.', 26.99, 'Ashlee Vance', 'Biographies & Memoirs', 'Ecco', 416, 'https://images-na.ssl-images-amazon.com/images/I/5112YFsXIJL._SX330_BO1,204,203,200_.jpg');

insert into books (id, name, description, price, author, genre, publisher, pageCount, imageUrl) values (1025, 'The Velvet Rage: Overcoming the Pain of Growing Up Gay in a Straight Man''s World, Second Edition', 'In The Velvet Rage, psychologist Alan Downs draws on his own struggle with shame and anger, contemporary research, and stories from his patients to passionately describe the stages of a gay man''s journey out of shame and offers practical and inspired strategies to stop the cycle of avoidance and self-defeating behavior. The Velvet Rage is an empowering book that has already changed the public discourse on gay culture and helped shape the identity of an entire generation of gay men.', 11.43, 'Alan Downs', 'Gay & Lesbian Demographic Studies', 'Da Capo Lifelong Books', 272, 'https://images-na.ssl-images-amazon.com/images/I/51Mzb02yQDL._SX329_BO1,204,203,200_.jpg');

insert into books (id, name, description, price, author, genre, publisher, pageCount, imageUrl) values (1026, 'Shadow Flight (A Shadow Riders Novel)', 'Nicoletta Gomez was a terrified teenager when Taviano Ferraro and his brother saved her life. Ever since, she’s been trying to rise above what was done to her, molding herself into a survivor under the protective eyes of the Ferraro family. All the while, she’s been falling hopelessly in love with the man who knows her darkest secrets. With one look, Taviano knew that Nicoletta was his, just as he felt their shadows connect. But no matter how much he wanted to claim her, he knew she needed time to become her own woman. When Nicoletta once again finds herself in the sights of dangerous men, a split-second decision has Taviano breaking all of the Ferraro family’s rules to keep her safe. And as far as he’s concerned, the reward is more than worth the risk.', 5.31, 'Christine Feehan', 'Paranormal Romance', 'Berkley', 432, 'https://images-na.ssl-images-amazon.com/images/I/517eLVu9cSL._SX308_BO1,204,203,200_.jpg');

insert into books (id, name, description, price, author, genre, publisher, pageCount, imageUrl) values (1027, 'The All Souls Trilogy Boxed Set', 'With more than two million copies sold in the United States, the novels of the number one New York Times–bestselling All Souls Trilogy have landed on all the major bestseller lists, garnered rave reviews, and spellbound legions of loyal fans. Now all three novels are available in an elegantly designed boxed set that’s perfect for fans and newcomers alike.', 48.60, 'Deborah Harkness', 'Fantasy', 'Penguin Books', 1760, 'https://images-na.ssl-images-amazon.com/images/I/611GZxb6TAL._SX382_BO1,204,203,200_.jpg');

insert into books (id, name, description, price, author, genre, publisher, pageCount, imageUrl) values (1028, '100 Amazing Patterns: An Adult Coloring Book with Fun, Easy, and Relaxing Coloring Pages', 'Our 100 Amazing Patterns coloring book is an incredible collection of relaxing and easy-to-color patterns. Enjoy the symmetrical and simple beauty of lovely flowers, elegant floral patterns, fun geometric shapes, adorable animals, and much more! With 100 different patterns to color and a variety of themes, you will always have something different to color. If you love mandala coloring books, then you will love this reimagined mandala experience. We have combined the symmetrical beauty of mandalas with the enjoyment of coloring “full-frame” images. By eliminating the whitespace commonly found in mandala books, we have given you even more to color!', 9.99, 'Jade Summer', 'Pop Culture Art', 'Independently published', 203, 'https://images-na.ssl-images-amazon.com/images/I/613WWuy5wjL._SX384_BO1,204,203,200_.jpg');

insert into books (id, name, description, price, author, genre, publisher, pageCount, imageUrl) values (1029, 'Piano Book for Adult Beginners: Teach Yourself How to Play Famous Piano Songs, Read Music, Theory & Technique', 'Piano Professor, Damon Ferrante guides you through how to play the piano with step-by-step lessons for beginners and 20 streaming video lessons. This easy-to-follow method, used by thousands of piano students and teachers, is designed to be interactive, engaging and fun.', 15.29, 'Damon Ferrante', 'Sheet Music & Scores', 'Steeplechase Arts', 122, 'https://images-na.ssl-images-amazon.com/images/I/51rGH1CV5BL._SX384_BO1,204,203,200_.jpg');




insert into stocks (productId, stock, reserved) values (1000, 11, 0);
insert into stocks (productId, stock, reserved) values (1001, 11, 0);
insert into stocks (productId, stock, reserved) values (1002, 12, 1);
insert into stocks (productId, stock, reserved) values (1003, 13, 2);
insert into stocks (productId, stock, reserved) values (1004, 14, 3);
insert into stocks (productId, stock, reserved) values (1005, 15, 4);
insert into stocks (productId, stock, reserved) values (1006, 16, 5);
insert into stocks (productId, stock, reserved) values (1007, 17, 6);
insert into stocks (productId, stock, reserved) values (1008, 18, 7);
insert into stocks (productId, stock, reserved) values (1009, 19, 8);
insert into stocks (productId, stock, reserved) values (1010, 20, 9);
insert into stocks (productId, stock, reserved) values (1011, 21, 10);
insert into stocks (productId, stock, reserved) values (1012, 22, 0);
insert into stocks (productId, stock, reserved) values (1013, 23, 1);
insert into stocks (productId, stock, reserved) values (1014, 24, 2);
insert into stocks (productId, stock, reserved) values (1015, 25, 3);
insert into stocks (productId, stock, reserved) values (1016, 26, 4);
insert into stocks (productId, stock, reserved) values (1017, 27, 5);
insert into stocks (productId, stock, reserved) values (1018, 28, 6);
insert into stocks (productId, stock, reserved) values (1019, 29, 7);
insert into stocks (productId, stock, reserved) values (1021, 1, 1);
insert into stocks (productId, stock, reserved) values (1022, 2, 2);
insert into stocks (productId, stock, reserved) values (1023, 3, 0);
insert into stocks (productId, stock, reserved) values (1024, 4, 1);
insert into stocks (productId, stock, reserved) values (1025, 5, 2);
insert into stocks (productId, stock, reserved) values (1026, 6, 3);
insert into stocks (productId, stock, reserved) values (1027, 7, 4);
insert into stocks (productId, stock, reserved) values (1028, 8, 5);
insert into stocks (productId, stock, reserved) values (1029, 9, 6);

